### ISSUE TITLE
Linkedin: Connection aborted

### ISSUE THREAD

**Issue by gauravg84** [krishpranav/socialosint#1]
Hello,
I am trying to use this tool, However, its keeps on saying that "**_Linkedin: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))←[0m_**"

Can you please help?
Thanks

**Comment by krishpranav** [comment]
hi @gauravg84 can you screenshot and send me the error??

**Comment by gauravg84** [comment]
![Screenshot 2021-07-20 074943](https://user-images.githubusercontent.com/59166019/126268527-471db883-5d54-4790-a0e8-bb8d3de1bc95.png)
Hi,
Here is the screenshot of the error.

**Comment by krishpranav** [comment]
run these steps:
```sh
git clone https://github.com/krishpranav/socialosint
cd socialosint
python3 -m pip install -r requirements.txt
python3 -m venv env
source env/bin/activate
python3 socialosint.py
```

**make sure you have entered all your credentials in credentials.json**

**Comment by gauravg84** [comment]
![Screenshot 2021-07-20 200940](https://user-images.githubusercontent.com/59166019/126375907-e8b672ee-3c14-42f3-b02c-8ea9d1c66912.png)

Hi. After following the step now the error message is this.

**Comment by krishpranav** [comment]
ok i will check the issue and fix it

**Comment by krishpranav** [comment]
![Untitled](https://user-images.githubusercontent.com/68631244/126586365-6d53cc8f-8723-44aa-a75c-c047ced7be75.png)

**Comment by krishpranav** [comment]
it works fine on my mac
did you enter your credentials in the credentials.json?

**Comment by krishpranav** [comment]
```json
    "linkedin":{
        "email":"email",
        "password":"password"
    }
```

you need to give your email and password in the linkedin section in credentials.json

**Comment by krishpranav** [comment]
i've updated this code
type :
git pull and try again

**Comment by gauravg84** [comment]
Thanks
